name: my_nikah_booking
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^5.0.2
  http: ^0.13.5
  rxdart: ^0.27.7
  textless: ^6.6.6
  transparent_image: ^2.0.0
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/splash-screen/
    - assets/animations/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: MaisonNeueExtended
      fonts:
        - asset: assets/fonts/MaisonNeueExtended-Bold.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.ttf
          weight: 500
